name: Source Plugin AWS Workflow

on:
  pull_request:
    paths:
      - "plugins/source/aws/**"
      - ".github/workflows/source_aws.yml"
  push:
    branches:
      - main
    paths:
      - "plugins/source/aws/**"
      - ".github/workflows/source_aws.yml"

jobs:
  plugins-source-aws:
    name: "plugins/source/aws"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./plugins/source/aws
    steps:
      - uses: actions/checkout@v3
        if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'cq-bot'
        with:
          fetch-depth: 2
          token: ${{ secrets.GH_CQ_BOT }}
      - uses: actions/checkout@v3
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'cq-bot')
        with:
          fetch-depth: 2
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/aws/go.mod
          cache: true
          cache-dependency-path: plugins/source/aws/go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          working-directory: plugins/source/aws
          args: "--config ../../.golangci.yml"
      - name: Get dependencies
        run: go get -t -d ./...
      - name: Build
        run: go build .
      - name: Test
        run: make test
      - name: gen-code
        if: github.event_name == 'pull_request'
        run: make gen-code
      - name: Fail if code generation changed services
        if: github.event_name == 'pull_request' && github.event.pull_request.user.login != 'cq-bot'
        run: test "$(git status -s ./resources/services | wc -l)" -eq 0
      - name: gen-docs
        if: github.event_name == 'pull_request'
        run: make gen-docs
      - name: Fail if docs are changed
        if: github.event_name == 'pull_request' && github.event.pull_request.user.login != 'cq-bot'
        run: test "$(git status -s ./docs/tables | wc -l)" -eq 0
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'cq-bot'
        with:
          commit_message: "chore: Update code and docs"
          branch: ${{ github.event.client_payload.pull_request.head.ref }}
  validate-release:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.19.1-release-cache-${{ hashFiles('plugins/source/aws/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-1.19.1-release-cache-plugins-source-aws
      - name: Set up Go
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: actions/setup-go@v3
        with:
          go-version-file: plugins/source/aws/go.mod
      - name: Install GoReleaser
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser-pro
          version: latest
          install-only: true
      - name: Run GoReleaser Dry-Run
        if: startsWith(github.head_ref, 'release-please--branches--main--components') || github.event_name == 'push'
        run: goreleaser release --snapshot --rm-dist --skip-validate --skip-publish --skip-sign -f ./plugins/source/aws/.goreleaser.yaml
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
